GET http://localhost:3001/api/patients/

###
GET http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667

###
POST http://localhost:3001/api/patients/ HTTP/1.1
content-type: application/json

{
  "name": "Test Name",
  "dateOfBirth": "1994-01-01",
  "ssn": "999999-999X",
  "gender": "female",
  "occupation": "Test occupation"
}

###
POST http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
content-type: application/json

{
  "type": "HealthCheck",
  "description": "Test Description",
  "date": "1994-01-01",
  "specialist": "Test Specialist",
  "diagnosisCodes": [
    "Z57.1",
    "S62.5"
  ],
  "healthCheckRating": "wadwa"
}